"""modiefied prescription table

Revision ID: f8961c5940d8
Revises: b6e0e99c646c
Create Date: 2026-01-24 00:02:59.792970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8961c5940d8'
down_revision: Union[str, Sequence[str], None] = 'b6e0e99c646c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('prescriptions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prescriptions', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'prescriptions', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_column('prescriptions', 'rejection_reason')
    op.drop_column('prescriptions', 'reviewed_at')
    op.drop_column('prescriptions', 'reviewed_by')
    # ### end Alembic commands ###
